name: Deploy on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WIEMANN_CV }}'
          channelId: live
          projectId: wiemann-cv
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
